import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";

import { Footer } from "./(home)/modules/Footer";
import { SalesBanner } from "./(home)/modules/SalesBanner";
import { Banner } from "./(home)/modules/Banner";
import { cookies } from "next/headers";
import { getCart } from "@/lib/shopify";
import { CartProvider } from "@/context/cart";
import { CartDialog } from "@/modules/cart/CartDialog";
import PurchaseNotificationWidget from "@/components/purchase-notification-widget/notification-widget";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cartId = cookies().get("cartId")?.value;
  const cartPromise = getCart(cartId);

  return (
    <html lang="en">
      <body className={`${poppins.className} bg-[#fefae0] relative`}>
        <SalesBanner />
        <CartProvider cartPromise={cartPromise}>
          <Banner />
          {children}
          <CartDialog />
        </CartProvider>
        <Footer />
        <PurchaseNotificationWidget />
      </body>
    </html>
  );
}
